ProjeDeneme1/ProjeDeneme1/Areas/Admin/Controllers/MainController.cs
using ProjeDeneme1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjeDeneme1.Areas.Admin.Controllers
{
   
    [Authorize(Roles ="Admin")]
    [Language]
    public class MainController : Controller
    {
        // GET: Admin/Main
        private performansEntities db = new performansEntities();


        public ActionResult Index()
        {
            var bilgi =
                  from cb in db.CalisanBilgileri
                  join pp in db.performansPuan
                  on cb.CalisanID equals pp.CalisanID
                  join cu in db.CalisanUnvan
                  on cb.CalisanUnvanID equals cu.CalisanUnvanID
                  join pa in db.PerformansAciklama
                  on pp.IsID equals pa.IsID
                  where cb.CalisanDurum == true
                  select new CalisanViewModel { CalisanBilgileri = cb, performansPuan = pp, CalisanUnvan = cu, PerformansAciklama = pa };


            return View(bilgi);

        }
        public ActionResult CalisanDuzenle()
        {
            var calisanBilgileri =
               from cb in db.CalisanBilgileri
               join cu in db.CalisanUnvan
               on cb.CalisanUnvanID equals cu.CalisanUnvanID
               where cb.CalisanDurum == true
               select new CalisanViewModel { CalisanBilgileri = cb, CalisanUnvan = cu };


            return View(calisanBilgileri);
        }

        public ActionResult Duzenle()
        {
            return View();
        }


        public ActionResult CalisanSil()
        {
            //var calisanBilgileri = db.CalisanBilgileri.Include(c => c.CalisanUnvan);
            var calisanBilgileri =
                from cb in db.CalisanBilgileri
                join cu in db.CalisanUnvan
                on cb.CalisanUnvanID equals cu.CalisanUnvanID
                where cb.CalisanDurum == true
                select new CalisanViewModel { CalisanBilgileri = cb, CalisanUnvan = cu };


            return View(calisanBilgileri);
        }
        public ActionResult Sil()
        {

            return View();
        }


        public ActionResult IsEkle()
        {
            var bilgi =
                from cb in db.CalisanBilgileri
                join pp in db.performansPuan
                on cb.CalisanID equals pp.CalisanID
                join cu in db.CalisanUnvan
                on cb.CalisanUnvanID equals cu.CalisanUnvanID
                where cb.CalisanDurum == true
                select new CalisanViewModel { CalisanBilgileri = cb, performansPuan = pp, CalisanUnvan = cu };

            return View(bilgi);

        }
        public ActionResult Iekle()
        {
            return View();
        }

        public ActionResult IsGuncelle()
        {
            var bilgi =
                 from cb in db.CalisanBilgileri
                 join pp in db.performansPuan
                 on cb.CalisanID equals pp.CalisanID
                 join cu in db.CalisanUnvan
                 on cb.CalisanUnvanID equals cu.CalisanUnvanID
                 where cb.CalisanDurum == true
                 select new CalisanViewModel { CalisanBilgileri = cb, performansPuan = pp, CalisanUnvan = cu };

            return View(bilgi);
        }
        public ActionResult Iguncelle()
        {
            return View();
        }
    }
}

ProjeDeneme1/ProjeDeneme1/Areas/Admin/Views/Main/CalisanDuzenle.cshtml
@model IEnumerable<ProjeDeneme1.Models.CalisanViewModel>
@{
    //ViewBag.Title = "CalisanDuzenle";
    Layout = "~/Areas/Admin/Views/Shared/Layout.cshtml";
}



<html>
<head>

</head>
<body>

    <div class="col-lg-7">
        <table class="table table-striped">
            <tr>
                <td class="danger">Çalışan Ad</td>
                <td class="warning">Çalışan Soyad</td>
                <td class="success">Ünvan</td>
                <td class="active">Çalışan Düzenle</td>

            </tr>

            @foreach (var item in Model)
            {

                <tr>
                    <td>@item.CalisanBilgileri.CalisanAd</td>
                    <td>@item.CalisanBilgileri.CalisanSoyad</td>
                    <td>@item.CalisanUnvan.CalisanUnvan1</td>
                    <td>@Html.ActionLink("Düzenle", "Duzenle","Main",new { id = item.CalisanBilgileri.CalisanID })</td>
                </tr>
            }


        </table>
    </div>


</body>
</html>

ProjeDeneme1/ProjeDeneme1/Areas/Admin/Views/Main/CalisanSil.cshtml
@model IEnumerable<ProjeDeneme1.Models.CalisanViewModel>
@{
    //ViewBag.Title = "CalisanDuzenle";
    Layout = "~/Areas/Admin/Views/Shared/Layout.cshtml";
}



<html>
<head>

</head>
<body>

    <div class="col-lg-7">
        <table class="table table-striped">
            <tr>
                <td class="danger">Çalışan Ad</td>
                <td class="warning">Çalışan Soyad</td>
                <td class="success">Ünvan</td>
                <td class="active">Çalışan Sil</td>

            </tr>

            @foreach (var item in Model)
            {

                <tr>
                    <td>@item.CalisanBilgileri.CalisanAd</td>
                    <td>@item.CalisanBilgileri.CalisanSoyad</td>
                    <td>@item.CalisanUnvan.CalisanUnvan1</td>
                    <td>@Html.ActionLink("Sil", "Sil", "Main", new { id = item.CalisanBilgileri.CalisanID })</td>
                </tr>
            }


        </table>
    </div>


</body>
</html>

ProjeDeneme1/ProjeDeneme1/Areas/Admin/Views/Main/Duzenle.cshtml
@model IEnumerable<ProjeDeneme1.Models.CalisanBilgileri>
@{
    //ViewBag.Title = "Duzenle";
    Layout = "~/Areas/Admin/Views/Shared/Layout.cshtml";
}

<h2>Duzenle</h2>

<body>
    <div class="col-lg-1">
    </div>

    <div class="col-lg-3">
        <div class="table-bordered">

            <div class="jumbotron" style="background:#FFFFFF">

                <input type="text" class="form-control" placeholder="Çalışan Adı">
                <br />
                <input type="text" class="form-control" placeholder="Çalışan Soyadı">
                <br />
                <input type="text" class="form-control" placeholder="Çalışan Ünvan" />
                <div class="col-lg-3">
                </div>
                <div class="col-lg-1">

                    <button type="button" class="btn btn-info"> Düzenle </button>
                </div>

            </div>
        </div>

    </div>

</body>


@*<form class="navbar-form navbar-right">*@

ProjeDeneme1/ProjeDeneme1/Areas/Admin/Views/Main/Iekle.cshtml
@model IEnumerable<ProjeDeneme1.Models.CalisanViewModel>
@{
    ViewBag.Title = "Iekle";
    Layout = "~/Areas/Admin/Views/Shared/Layout.cshtml";
}



<div class="col-lg-1">
</div>

<div class="col-lg-3">
    <div class="table-bordered">

        <div class="jumbotron" style="background:#FFFFFF">

            @Html.Label("Çalışan Ad :")
            <input type="text" class="form-control" placeholder="Çalışan Adı">
            <br />

            @Html.Label("Çalışan Soyad :")
            <input type="text" class="form-control" placeholder="Çalışan Soyadı">
            <br />
            @Html.Label("Çalışan Ünvan :")
            <input type="text" class="form-control" placeholder="Çalışan Ünvan" />
            <br />
            @Html.Label("İş Numarası :")
            <input type="text" class="form-control" placeholder="İş Numarası" />
            <div class="col-lg-8">
            </div>
            <div class="col-lg-4">

                <button type="button" class="btn btn-info"> Ekle </button>
            </div>

        </div>
    </div>

</div>

ProjeDeneme1/ProjeDeneme1/Areas/Admin/Views/Main/Iguncelle.cshtml
@{
    ViewBag.Title = "Iguncelle";
    Layout = "~/Areas/Admin/Views/Shared/Layout.cshtml";
}

<div class="col-lg-1">
</div>

<div class="col-lg-3">
    <div class="table-bordered">

        <div class="jumbotron" style="background:#FFFFFF">

            @Html.Label("Çalışan Ad :")
            <input type="text" class="form-control" placeholder="Çalışan Adı">
            <br />

            @Html.Label("Çalışan Soyad :")
            <input type="text" class="form-control" placeholder="Çalışan Soyadı">
            <br />
            @Html.Label("Çalışan Ünvan :")
            <input type="text" class="form-control" placeholder="Çalışan Ünvan" />
            <br />
            @Html.Label("İş Numarası :")
            <input type="text" class="form-control" placeholder="İş Numarası" />
            <div class="col-lg-8">
            </div>
            <div class="col-lg-4">

                <button type="button" class="btn btn-info"> Güncelle </button>
            </div>

        </div>
    </div>

</div>

ProjeDeneme1/ProjeDeneme1/Areas/Admin/Views/Main/Index.cshtml
@model IEnumerable<ProjeDeneme1.Models.CalisanViewModel>

@{
    //ViewBag.Title = "AdminEkrani";
    Layout = "~/Areas/Admin/Views/Shared/Layout.cshtml";
}



<html>
<head>

</head>
<body>

    <div class="col-lg-7">
        <table class="table table-striped">
            <tr>
                <td class="danger">Çalışan Ad</td>
                <td class="warning">Çalışan Soyad</td>
                <td class="success">Ünvan</td>
                <td class="active">İş Numarası</td>
                <td class="danger">Puan</td>
                <td class="warning">Açıklama</td>

            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.CalisanBilgileri.CalisanAd</td>
                    <td>@item.CalisanBilgileri.CalisanSoyad</td>
                    <td>@item.CalisanUnvan.CalisanUnvan1</td>
                    <td>@item.performansPuan.IsID</td>
                    <td>@item.performansPuan.CalisanPuan</td>
                    <td>@item.PerformansAciklama.Aciklama</td>
                </tr>
            }
        </table>
    </div>
</body>
</html>

ProjeDeneme1/ProjeDeneme1/Areas/Admin/Views/Main/IsEkle.cshtml
@model IEnumerable<ProjeDeneme1.Models.CalisanViewModel>
@{
    ViewBag.Title = "IsEkle";
    Layout = "~/Areas/Admin/Views/Shared/Layout.cshtml";
}

<div class="col-lg-7">
    <table class="table table-striped">
        <tr>
            <td class="danger">Çalışan Ad</td>
            <td class="warning">Çalışan Soyad</td>
            <td class="success">Ünvan</td>
            <td class="active">İş Numarası</td>
            <td class="warning">İş Ekle</td>

        </tr>
        @foreach (var item in Model)
            {
            <tr>
                <td>@item.CalisanBilgileri.CalisanAd</td>
                <td>@item.CalisanBilgileri.CalisanSoyad</td>
                <td>@item.CalisanUnvan.CalisanUnvan1</td>
                <td>@item.performansPuan.IsID</td>
                <td>@Html.ActionLink("İş Ekle", "Iekle","Main", new { id = item.CalisanBilgileri.CalisanID })</td>
            </tr>
        }

    </table>
</div>

ProjeDeneme1/ProjeDeneme1/Areas/Admin/Views/Main/IsGuncelle.cshtml
@model IEnumerable<ProjeDeneme1.Models.CalisanViewModel>
@{
    ViewBag.Title = "IsGuncelle";
    Layout = "~/Areas/Admin/Views/Shared/Layout.cshtml";
}


<div class="col-lg-7">
    <table class="table table-striped">
        <tr>
            <td class="danger">Çalışan Ad</td>
            <td class="warning">Çalışan Soyad</td>
            <td class="success">Ünvan</td>
            <td class="active">İş Numarası</td>
            <td class="warning">İş Güncelle</td>

        </tr>
        @foreach (var item in Model)
            {
            <tr>
                <td>@item.CalisanBilgileri.CalisanAd</td>
                <td>@item.CalisanBilgileri.CalisanSoyad</td>
                <td>@item.CalisanUnvan.CalisanUnvan1</td>
                <td>@item.performansPuan.IsID</td>
                <td>@Html.ActionLink("İş Güncelle", "Iguncelle","Main", new { id = item.CalisanBilgileri.CalisanID })</td>
            </tr>
        }

    </table>
</div>

ProjeDeneme1/ProjeDeneme1/Areas/Admin/Views/Main/Sil.cshtml
@model IEnumerable<ProjeDeneme1.Models.CalisanBilgileri>
@{
    //ViewBag.Title = "Sil";
    Layout = "~/Areas/Admin/Views/Shared/Layout.cshtml";
}

<div class="col-lg-1">
</div>

<div class="col-lg-3">
    <div class="table-bordered">

        <div class="jumbotron" style="background:#FFFFFF">

            <input type="text" class="form-control" placeholder="Çalışan Adı">
            <br />
            <input type="text" class="form-control" placeholder="Çalışan Soyadı">
            <br />
            <input type="text" class="form-control" placeholder="Çalışan Ünvan" />
            <div class="col-lg-3">
            </div>
            <div class="col-lg-1">

                <button type="button" class="btn btn-info"> Sil </button>
            </div>

        </div>
    </div>

</div>