ProjeDeneme1/ProjeDeneme1/Areas/Admin/Controllers/RolYonetimController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using ProjeDeneme1.Areas.Admin.Models;
using ProjeDeneme1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjeDeneme1.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RolYonetimController : Controller
    {
        ApplicationDbContext context = new ApplicationDbContext();

        // GET: Admin/RolYonetim
        public ActionResult Index()
        {
            var roleStore = new RoleStore<IdentityRole>(context);
            var roleManager = new RoleManager<IdentityRole>(roleStore);


            var model=roleManager.Roles.ToList();
                return View(model);
        }
        public ActionResult RolEkle()
        {
            
            return View();
        }
        [HttpPost]
        public ActionResult RolEkle(RolEkleModel rol)
        {
            var roleStore = new RoleStore<IdentityRole>(context);
            var roleManager = new RoleManager<IdentityRole>(roleStore);

            if(roleManager.RoleExists(rol.RolAd)==false)
            {
                roleManager.Create(new IdentityRole(rol.RolAd));
            }
            return RedirectToAction("Index");
        }
        public ActionResult RolKullaniciEkle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult RolKullaniciEkle(RolKullaniciEkleModel model)
        {
            var roleStore = new RoleStore<IdentityRole>(context);
            var roleManager = new RoleManager<IdentityRole>(roleStore);

            var userStore = new UserStore<ApplicationUser>(context);
            var userManager = new UserManager<ApplicationUser>(userStore);
            var kullanici = userManager.FindByName(model.KullaniciAdi);

            if(!userManager.IsInRole(kullanici.Id,model.RolAdi))
            {
                userManager.AddToRole(kullanici.Id, model.RolAdi);
            }
            

    
            return RedirectToAction("Index");
        }
    }
}

ProjeDeneme1/ProjeDeneme1/Areas/Admin/Views/RolYonetim/Index.cshtml
@model List< Microsoft.AspNet.Identity.EntityFramework.IdentityRole>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/Layout.cshtml";
}

<h2>Index</h2>

<ul>

    @foreach(var item in Model)
    {
        <li>
            @item.Name - @item.Users.Count
        </li>
    }
</ul>
@Html.ActionLink("Yeni rol ekle","RolEkle")

ProjeDeneme1/ProjeDeneme1/Areas/Admin/Views/RolYonetim/RolEkle.cshtml
@model ProjeDeneme1.Models.RolEkleModel
@{
    ViewBag.Title = "RolEkle";
    Layout = "~/Areas/Admin/Views/Shared/Layout.cshtml";
}

<h2>RolEkle</h2>

@using (Html.BeginForm("RolEkle","RolYonetim",FormMethod.Post))
{
    @Html.TextBoxFor(m=>m.RolAd)
    <input type="submit"/>
}

ProjeDeneme1/ProjeDeneme1/Areas/Admin/Views/RolYonetim/RolKullaniciEkle.cshtml
@model ProjeDeneme1.Areas.Admin.Models.RolKullaniciEkleModel

@{
    ViewBag.Title = "RolKullaniciEkle";
    Layout = "~/Areas/Admin/Views/Shared/Layout.cshtml";
}

<h2>RolKullaniciEkle</h2>

@using (Html.BeginForm("RolKullaniciEkle", "RolYonetim", FormMethod.Post))
{
    @Html.LabelFor(m=>m.KullaniciAdi)  @Html.TextBoxFor(m=>m.KullaniciAdi)
      <br/>
    @Html.LabelFor(m => m.RolAdi)  @Html.TextBoxFor(m => m.RolAdi)
    <br />
    <input type="submit"/>
}